using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator.Infrastructure;

namespace Showcase.Generator.Level4;

/// <summary>
/// Level 4 — AutoService 生成器（复杂聚合）
///
/// 引入 API：
///   - providers.Collect()  将所有匹配节点聚合后，一次性生成单个文件
///
/// 生成内容：
///   所有 [AutoService] 类 → 聚合生成全局 Service 静态类（Service.g.cs）
///
/// 关键教学：
///   - .Collect() 等所有节点收集完后才触发生成，与逐个生成（Level 0~3）的对比：
///       不用 Collect → 每个类触发一次，生成各自独立的文件
///       用 Collect   → 所有类汇总后生成一个聚合文件（Service.g.cs）
/// </summary>
[Generator]
public class AutoServiceGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Showcase.Core.AutoServiceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.GenerateMode", out var mode);
                return GeneratorConfig.ParseMode(mode);
            }
        );

        var providers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassForSourceGen(ctx)
            )
            .Where(static t => t != null)
            .Select(static (t, _) => t!);

        // 关键点：.Collect() 聚合所有 [AutoService] 类，一次性生成 Service.g.cs
        context.RegisterSourceOutput(
            providers.Collect().Combine(configProvider),
            static (ctx, t) => GenerateCode(ctx, t.Left, t.Right)
        );
    }

    private static INamedTypeSymbol? GetClassForSourceGen(GeneratorSyntaxContext context)
    {
        var syntax = (ClassDeclarationSyntax)context.Node;

        foreach (var attrList in syntax.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol attrSymbol)
                continue;
            if (attrSymbol.ContainingType.ToDisplayString() != AttributeFullName)
                continue;
            return context.SemanticModel.GetDeclaredSymbol(syntax) as INamedTypeSymbol;
        }

        return null;
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol> items,
        GenerateMode mode)
    {
        if (items.IsEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generator: AutoServiceGenerator (Level 4)");
        sb.AppendLine("namespace Showcase.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class Service");
        sb.AppendLine("    {");

        // 记录第一个类的源文件路径（用于 WriteFile 模式）
        string? sourceFilePath = null;

        foreach (var symbol in items)
        {
            if (sourceFilePath == null)
            {
                var location = symbol.Locations.FirstOrDefault();
                sourceFilePath = location?.SourceTree?.FilePath;
            }

            var typeFullName = symbol.ToDisplayString();
            var propName = GetCustomName(symbol) ?? symbol.Name;
            var fieldName = char.ToLowerInvariant(propName[0]) + propName.Substring(1);

            sb.AppendLine($"        // {typeFullName}");
            sb.AppendLine($"        private static bool _{fieldName}_initialized;");
            sb.AppendLine($"        private static {typeFullName} _{fieldName};");
            sb.AppendLine();
            sb.AppendLine($"        public static {typeFullName} {propName}");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (!_{fieldName}_initialized)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    _{fieldName} = new {typeFullName}();");
            sb.AppendLine($"                    _{fieldName}_initialized = true;");
            sb.AppendLine("                }");
            sb.AppendLine($"                return _{fieldName};");
            sb.AppendLine("            }");
            sb.AppendLine("            set");
            sb.AppendLine("            {");
            sb.AppendLine($"                _{fieldName} = value;");
            sb.AppendLine($"                _{fieldName}_initialized = true;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        var source = sb.ToString();
        var fileName = "Service.g.cs";

        if (mode == GenerateMode.WriteFile && sourceFilePath != null)
        {
            FileWriter.WriteToPhysicalFile(context, sourceFilePath, fileName, source, "SVC");
        }
        else
        {
            context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string? GetCustomName(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != AttributeFullName) continue;
            foreach (var namedArg in attr.NamedArguments)
                if (namedArg.Key == "FieldName" && namedArg.Value.Value is string name)
                    return name;
        }
        return null;
    }
}
