// <auto-generated/>
// Generator: EventInterfaceGenerator (Level 5)
namespace Showcase.Level5
{
    /// <summary>事件 ID 常量（FNV-1a 哈希，负数域）</summary>
    public static class GameEvents
    {
        public const int OnPlayerDied = -992114595;
        public const int OnScoreChanged = -362662754;
        public const int OnLevelComplete = -1582685545;
    }

    /// <summary>事件分发器：将 int ID 映射到接口方法调用</summary>
    public static class GameEventsDispatcher
    {
        private static Showcase.Level5.IGameEvents? _handler;
        public static void Register(Showcase.Level5.IGameEvents handler) => _handler = handler;

        public static void Dispatch(int eventId, object? arg = null)
        {
            if (_handler == null) return;
            switch (eventId)
            {
                case GameEvents.OnPlayerDied:
                    _handler.OnPlayerDied((string)arg!); break;
                case GameEvents.OnScoreChanged:
                    _handler.OnScoreChanged((int)arg!); break;
                case GameEvents.OnLevelComplete:
                    _handler.OnLevelComplete(); break;
            }
        }
    }

    /// <summary>事件 Helper：便捷触发方法</summary>
    public static class GameEventsHelper
    {
        public static void OnPlayerDied(string playerName) =>
            GameEventsDispatcher.Dispatch(GameEvents.OnPlayerDied, playerName);
        public static void OnScoreChanged(int newScore) =>
            GameEventsDispatcher.Dispatch(GameEvents.OnScoreChanged, newScore);
        public static void OnLevelComplete() =>
            GameEventsDispatcher.Dispatch(GameEvents.OnLevelComplete, null);
    }
}
