// <auto-generated>
//     此代码由 EventExecuteGenerator 自动生成
//     不要手动修改此文件
// </auto-generated>

/// <summary>
/// BaseEvent 事件执行抽象声明（自动生成）
/// </summary>
public abstract partial class BaseEvent
{
    /// <summary>
    /// 执行事件（无返回值），由子类实现具体分发逻辑
    /// </summary>
    public abstract void Execute(Luban.BeanBase caller);
}
