// <auto-generated/>
// Generator: LogSourceGenerator (Level 0)
namespace Showcase.Level0
{
    public partial class Level0Demo
    {
        private static class Debug
        {
            private const string Tag = "Level0Demo";

#if UNITY_EDITOR
            private const string LogPrefix = "<color=#00FF00FF>[Level0Demo]</color>";
            private const string WarningPrefix = "<color=#FFFF00FF>[Level0Demo]</color>";
            private const string ErrorPrefix = "<color=#FF0000FF>[Level0Demo]</color>";
#else
            private const string LogPrefix = "[Level0Demo]";
            private const string WarningPrefix = "[Level0Demo]";
            private const string ErrorPrefix = "[Level0Demo]";
#endif

            [System.Diagnostics.Conditional("UNITY_EDITOR")]
            public static void Log(object msg) =>
                UnityEngine.Debug.Log($"{LogPrefix} {msg}");

            public static void LogWarning(object msg) =>
                UnityEngine.Debug.LogWarning($"{WarningPrefix} {msg}");

            public static void LogError(object msg) =>
                UnityEngine.Debug.LogError($"{ErrorPrefix} {msg}");

            public static void LogException(System.Exception ex) =>
                UnityEngine.Debug.LogException(ex);
        }
    }
}