using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator.Infrastructure;

namespace Showcase.Generator.Level1;

/// <summary>
/// Level 1 — AutoProperty 生成器（字段驱动）
///
/// 引入 API：
///   - FieldDeclarationSyntax  扫描字段而非类（与 Level 0 不同）
///   - VariableDeclarator      获取字段变量名
///
/// 生成内容：
///   [AutoProperty] private int _count;
///     → public int Count { get => _count; set => _count = value; }
///
/// 关键教学：
///   - SyntaxNode 类型：ClassDeclarationSyntax vs FieldDeclarationSyntax
///   - _camelCase → PascalCase 的转换（去掉前缀下划线，首字母大写）
///   - 按类型分组：将同一个类的所有字段聚合到一个生成文件
/// </summary>
[Generator]
public class AutoPropertyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Showcase.Core.AutoPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 读取 MSBuild 配置
        var configProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.GenerateMode", out var mode);
                return GeneratorConfig.ParseMode(mode);
            }
        );

        // 关键点：predicate 扫描 FieldDeclarationSyntax，而不是 ClassDeclarationSyntax
        var providers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is FieldDeclarationSyntax,
                transform: static (ctx, _) => GetFieldForSourceGen(ctx)
            )
            .Where(static t => t.found)
            .Select(static (t, _) => t);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(providers.Collect()).Combine(configProvider),
            static (ctx, t) => GenerateCode(ctx, t.Left.Left, t.Left.Right, t.Right)
        );
    }

    private static (FieldDeclarationSyntax field, bool found, INamedTypeSymbol? containingType)
        GetFieldForSourceGen(GeneratorSyntaxContext context)
    {
        var field = (FieldDeclarationSyntax)context.Node;

        foreach (var attrList in field.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol attrSymbol)
                continue;

            if (attrSymbol.ContainingType.ToDisplayString() != AttributeFullName)
                continue;

            // 字段的父节点就是包含它的类型声明
            if (field.Parent is TypeDeclarationSyntax parentType)
            {
                var typeSymbol = context.SemanticModel.GetDeclaredSymbol(parentType) as INamedTypeSymbol;
                return (field, true, typeSymbol);
            }
        }

        return (field, false, null);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<(FieldDeclarationSyntax field, bool found, INamedTypeSymbol? containingType)> items,
        GenerateMode mode)
    {
        // 按所在类型分组，同一个类的所有 AutoProperty 字段生成到同一个文件
        var groups = items
            .Where(t => t.containingType != null)
            .GroupBy(t => t.containingType!, SymbolEqualityComparer.Default);

        foreach (var group in groups)
        {
            var classSymbol = (INamedTypeSymbol)group.Key;
            var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var typeName = classSymbol.TypeKind == TypeKind.Struct ? "struct" : "class";

            var nsOpen = string.IsNullOrEmpty(ns) ? "" : $"namespace {ns}\n{{";
            var nsClose = string.IsNullOrEmpty(ns) ? "" : "}";
            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generator: AutoPropertyGenerator (Level 1)");
            sb.AppendLine(nsOpen);
            sb.AppendLine($"{indent}public partial {typeName} {className}");
            sb.AppendLine($"{indent}{{");

            // 记录第一个字段的文件路径（用于 WriteFile 模式）
            string? sourceFilePath = null;

            foreach (var (field, _, _) in group)
            {
                sourceFilePath ??= field.SyntaxTree.FilePath;

                // 获取字段类型字符串（如 "int", "string", "UnityEngine.GameObject"）
                var typeStr = field.Declaration.Type.ToString();

                // 一条字段声明可能有多个变量：int _a, _b;
                foreach (var variable in field.Declaration.Variables)
                {
                    var fieldName = variable.Identifier.Text;
                    var propName = ToPropertyName(fieldName);

                    sb.AppendLine($"{indent}    public {typeStr} {propName}");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        get => {fieldName};");
                    sb.AppendLine($"{indent}        set => {fieldName} = value;");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();
                }
            }

            sb.AppendLine($"{indent}}}");
            sb.AppendLine(nsClose);

            var fileName = $"{className}.AutoProperty.g.cs";
            var source = sb.ToString();

            if (mode == GenerateMode.WriteFile && sourceFilePath != null)
            {
                FileWriter.WriteToPhysicalFile(context, sourceFilePath, fileName, source, "PROP");
            }
            else
            {
                context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }
        }
    }

    /// <summary>
    /// _camelCase → PascalCase
    /// 例：_health → Health，_maxSpeed → MaxSpeed
    /// </summary>
    private static string ToPropertyName(string fieldName)
    {
        var trimmed = fieldName.TrimStart('_');
        if (string.IsNullOrEmpty(trimmed)) return fieldName;
        return char.ToUpperInvariant(trimmed[0]) + trimmed.Substring(1);
    }
}
