// <auto-generated/>
// Generator: SchemaGenerator (Level 7 - Phase 1)
// 此文件描述所有模块的事件和工具契约，供 ModuleCodeGenerator 读取

namespace Showcase.Generated.ModuleMesh
{
    // ======= 事件契约 =======
    // [Event] player.spawned on Showcase.Level7.GameModule.OnPlayerSpawned
    // DataType: string

    // ======= 工具契约 =======
    // [Tool] calculate.damage on Showcase.Level7.GameModule.CalculateDamage
    // DataType: float

    /// <summary>所有模块事件和工具的编译期 Schema 注册表</summary>
    public static class ModuleMeshSchema
    {
        public static readonly string[] EventNames = {
            "player.spawned",
        };

        public static readonly string[] ToolNames = {
            "calculate.damage",
        };
    }
}
