// <auto-generated/>
// Generator: ModuleCodeGenerator (Level 7 - Phase 2)
using System;
using System.Collections.Generic;

namespace Showcase.Generated.ModuleMesh
{
    /// <summary>模块网格运行时注册表：事件订阅 + 工具调用胶水代码</summary>
    public static partial class ModuleMeshRegistry
    {
        // ======= 事件处理器注册 =======
        private static readonly Dictionary<string, Action<object>> _eventHandlers
            = new Dictionary<string, Action<object>>();

        // ======= 工具处理器注册 =======
        private static readonly Dictionary<string, Func<object, object>> _toolHandlers
            = new Dictionary<string, Func<object, object>>();

        /// <summary>注册 GameModule 的所有 [Event] 和 [Tool] 方法</summary>
        public static void RegisterGameModule(Showcase.Level7.GameModule instance)
        {
            _eventHandlers["player.spawned"] =
                data => instance.OnPlayerSpawned((string)data);
            _toolHandlers["calculate.damage"] =
                input => instance.CalculateDamage((float)input);
        }

        /// <summary>触发事件</summary>
        public static void Emit(string eventName, object data)
        {
            if (_eventHandlers.TryGetValue(eventName, out var handler))
                handler(data);
        }

        /// <summary>调用工具</summary>
        public static object? Call(string toolName, object input)
        {
            return _toolHandlers.TryGetValue(toolName, out var handler)
                ? handler(input) : null;
        }
    }
}
