using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator.Infrastructure;

namespace Showcase.Generator.Level3;

/// <summary>
/// Level 3b — MathGetter 生成器
///
/// 引入 API：
///   （与 MathSetter 共享技术栈，增加降维目标类型计算）
///
/// 生成内容：
///   [MathGetter(typeof(Vector3), axis: 3)]
///   static partial class Vector3Ext
///     → Get(axis1, axis2), GetXY(), GetXZ(), GetYZ(), GetXX(), GetYY(), GetZZ() 等
///
/// 关键教学：
///   - 目标类型降维：Vector3 → Vector2（通过正则替换类名中的数字）
///   - 命名轴组合：枚举 C(n,k) 生成 GetXY / GetXZ / GetYZ 等
///   - 同名方法复用：GetXX(target) → Get(target, 0, 0)
/// </summary>
[Generator]
public class MathGetterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Showcase.Core.MathType.MathGetterAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.GenerateMode", out var mode);
                return GeneratorConfig.ParseMode(mode);
            }
        );

        var results = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (t, _) => t is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: static (t, _) => GetClassDeclaration(t)
            )
            .Where(static t => t.Found);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(results.Collect()).Combine(configProvider),
            static (ctx, t) => GenerateCode(ctx, t.Left.Left, t.Left.Right, t.Right)
        );
    }

    private static GetterInfo GetClassDeclaration(GeneratorSyntaxContext context)
    {
        var syntax = (ClassDeclarationSyntax)context.Node;

        foreach (var attrList in syntax.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol attrSymbol)
                continue;
            if (attrSymbol.ContainingType.ToDisplayString() != AttributeFullName)
                continue;

            var args = attr.ArgumentList?.Arguments;
            if (args == null || args.Value.Count < 1) continue;

            // target: typeof(Vector3)
            var targetType = args.Value[0].Expression is TypeOfExpressionSyntax t0
                ? context.SemanticModel.GetTypeInfo(t0.Type).Type
                : null;
            if (targetType == null) continue;

            var targetName = targetType.ToDisplayString();

            // axis: 从参数或类名推断
            var axis = 0;
            if (args.Value.Count > 1 && args.Value[1].Expression is LiteralExpressionSyntax axisLit)
                axis = int.Parse(axisLit.Token.ValueText);
            if (axis == 0)
            {
                var match = MathTypeUtils.NumberRegex.Match(syntax.Identifier.Text);
                if (match.Success) axis = int.Parse(match.Value);
            }
            if (axis == 0) axis = 2;

            return new GetterInfo
            {
                Syntax = syntax,
                Found = true,
                Axis = axis,
                Target = targetName,
                Namespaces = new List<string> { MathTypeUtils.GetTypeNamespace(targetType) },
            };
        }

        return default;
    }

    private static void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<GetterInfo> items,
        GenerateMode mode)
    {
        foreach (var info in items)
        {
            var semanticModel = compilation.GetSemanticModel(info.Syntax.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(info.Syntax) is not INamedTypeSymbol symbol)
                continue;

            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var staticClass = info.Syntax.Identifier.Text;
            var targetName = info.Target;
            var axis = info.Axis;
            var namespaces = info.Namespaces.Distinct();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generator: MathGetterGenerator (Level 3)");

            foreach (var ns in namespaces)
                sb.AppendIndent($"using {ns};");

            if (MathTypeUtils.NamespaceValid(namespaceName))
            {
                sb.AppendIndent($"namespace {namespaceName}");
                sb.AppendIndent("{");
            }

            sb.AppendIndent($"public static partial class {staticClass}");
            sb.AppendIndent("{");

            for (var i = 2; i <= axis; i++)
                MethodBase(sb, axis, i, targetName);

            sb.AppendIndent("}");

            if (MathTypeUtils.NamespaceValid(namespaceName))
                sb.AppendIndent("}");

            var source = sb.ToString();
            var fileName = $"{staticClass}.Getter.g.cs";

            if (mode == GenerateMode.WriteFile)
            {
                FileWriter.WriteToPhysicalFile(context, info.Syntax.SyntaxTree.FilePath, fileName, source, "MATH");
            }
            else
            {
                context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }
        }
    }

    private static void MethodBase(StringBuilder sb, int max, int count, string targetName)
    {
        var args = "";
        var execute = "";
        for (var i = 1; i < count + 1; i++)
        {
            args += $", int axis{i}";
            execute += $"target[axis{i}]";
            if (i < count) execute += ", ";
        }
        var reduceTargetName = MathTypeUtils.NumberRegex.Replace(targetName, count.ToString());
        sb.AppendIndent($"    public static {reduceTargetName} Get(this {targetName} target{args}) => new({execute});");

        // 与自身维度一致的组合没有意义
        if (count != max)
        {
            var combinations = MathTypeUtils.GenerateCombinations(max, count);
            foreach (var combination in combinations)
            {
                var up = "";
                execute = "";
                foreach (var i in combination)
                {
                    up += MathTypeUtils.Axis[i].up;
                    execute += $", {i}";
                }
                sb.AppendIndent(
                    $"    public static {reduceTargetName} Get{up}(this {targetName} target) => Get(target{execute});");
            }
        }

        // 同轴重复提取：GetXX, GetYY, GetZZ
        for (var i = 0; i < max; i++)
        {
            var up = "";
            execute = "";
            for (var j = 0; j < count; j++)
            {
                up += MathTypeUtils.Axis[i].up;
                execute += $", {i}";
            }
            sb.AppendIndent(
                $"    public static {reduceTargetName} Get{up}(this {targetName} target) => Get(target{execute});");
        }
    }

    private struct GetterInfo
    {
        public ClassDeclarationSyntax Syntax;
        public bool Found;
        public int Axis;
        public string Target;
        public List<string> Namespaces;
    }
}
