// <auto-generated/>
// Generator: AutoServiceGenerator (Level 4)
namespace Showcase.Generated
{
    public static partial class Service
    {
        // Showcase.Level4.AudioService
        private static bool _audioService_initialized;
        private static Showcase.Level4.AudioService _audioService;

        public static Showcase.Level4.AudioService AudioService
        {
            get
            {
                if (!_audioService_initialized)
                {
                    _audioService = new Showcase.Level4.AudioService();
                    _audioService_initialized = true;
                }
                return _audioService;
            }
            set
            {
                _audioService = value;
                _audioService_initialized = true;
            }
        }

        // Showcase.Level4.InputService
        private static bool _inputService_initialized;
        private static Showcase.Level4.InputService _inputService;

        public static Showcase.Level4.InputService InputService
        {
            get
            {
                if (!_inputService_initialized)
                {
                    _inputService = new Showcase.Level4.InputService();
                    _inputService_initialized = true;
                }
                return _inputService;
            }
            set
            {
                _inputService = value;
                _inputService_initialized = true;
            }
        }

    }
}
