// <auto-generated/>
// Generator: AutoImplementGenerator (Level 2)
namespace Showcase.Level2
{
    partial class Level2Demo
    {
        public string Name { get; set; }
        public int Level { get; set; }
        public float Health { get; set; }
    }
}
