using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator.Infrastructure;

namespace Showcase.Generator.Level2;

/// <summary>
/// Level 2 — AutoImplement 生成器（接口属性自动实现）
///
/// 引入 API：
///   - SemanticModel.GetDeclaredSymbol   获取类的语义符号
///   - INamedTypeSymbol.AllInterfaces    递归获取类实现的所有接口
///   - IPropertySymbol                   接口属性符号（区别于方法）
///   - SymbolDisplayFormat.FullyQualifiedFormat  生成完全限定类型名
///
/// 生成内容：
///   [AutoImplement]
///   partial class Foo : IBar
///     → 为 IBar 中所有未在 Foo 及其基类中实现的属性生成 { get; set; }
///
/// 关键教学：
///   - AllInterfaces vs Interfaces：前者包含继承链上的全部接口
///   - 基类已实现的属性检查：遍历 BaseType 链避免重复生成
///   - FullyQualifiedFormat：生成代码中使用完全限定名避免 using 冲突
/// </summary>
[Generator]
public class AutoImplementGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Showcase.Core.AutoImplementAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 读取 MSBuild 配置
        var configProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.GenerateMode", out var mode);
                return GeneratorConfig.ParseMode(mode);
            }
        );

        // 查找所有带 [AutoImplement] 特性的类
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds
                    && cds.AttributeLists.Count > 0,
                transform: static (ctx, _) => ExtractClassInfo(ctx)
            )
            .Where(static info => info != null);

        // 组合配置，逐个生成
        var combined = candidates.Combine(configProvider);

        context.RegisterSourceOutput(
            combined,
            static (spc, data) =>
            {
                var (info, mode) = data;
                if (info != null) GenerateCode(spc, info, mode);
            }
        );
    }

    private static ClassInfo? ExtractClassInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        // 检查是否有 [AutoImplement] 特性
        var hasAttr = false;
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == AttributeFullName)
            {
                hasAttr = true;
                break;
            }
        }
        if (!hasAttr) return null;

        // 收集所有接口的属性，排除已在基类中实现的
        var props = symbol.AllInterfaces
            .SelectMany(i => i.GetMembers().OfType<IPropertySymbol>())
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<IPropertySymbol>()
            .Where(prop => !IsPropertyImplementedInBaseClasses(symbol, prop))
            .ToList();

        return new ClassInfo
        {
            ClassName = symbol.Name,
            Namespace = symbol.ContainingNamespace?.IsGlobalNamespace == true
                ? null
                : symbol.ContainingNamespace?.ToDisplayString(),
            Properties = props,
            SourceFilePath = classDecl.SyntaxTree.FilePath,
        };
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ClassInfo info,
        GenerateMode mode)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generator: AutoImplementGenerator (Level 2)");

        var hasNs = !string.IsNullOrEmpty(info.Namespace);
        var indent = hasNs ? "    " : "";

        if (hasNs)
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}partial class {info.ClassName}");
        sb.AppendLine($"{indent}{{");

        // 生成属性：使用完全限定类型名避免 using 冲突
        foreach (var prop in info.Properties)
        {
            var type = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"{indent}    public {type} {prop.Name} {{ get; set; }}");
        }

        sb.AppendLine($"{indent}}}");

        if (hasNs)
        {
            sb.AppendLine("}");
        }

        // 确保使用 LF 换行符
        var source = sb.ToString().Replace("\r\n", "\n").Replace("\r", "\n");
        var fileName = $"{info.ClassName}.AutoImpl.g.cs";

        if (mode == GenerateMode.WriteFile)
        {
            FileWriter.WriteToPhysicalFile(context, info.SourceFilePath, fileName, source, "IMPL");
        }
        else
        {
            context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }

    /// <summary>
    /// 检查指定属性是否已在基类中实现
    /// </summary>
    private static bool IsPropertyImplementedInBaseClasses(
        INamedTypeSymbol symbol,
        IPropertySymbol property)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            var existing = current
                .GetMembers(property.Name)
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p =>
                    SymbolEqualityComparer.Default.Equals(p.Type, property.Type));

            if (existing != null) return true;
            current = current.BaseType;
        }
        return false;
    }

    private sealed class ClassInfo
    {
        public string ClassName { get; set; } = string.Empty;
        public string? Namespace { get; set; }
        public List<IPropertySymbol> Properties { get; set; } = new();
        public string SourceFilePath { get; set; } = string.Empty;
    }
}
