// <auto-generated/>
// Generator: MathSetterGenerator (Level 3)
using UnityEngine;
using System;
namespace Showcase.Level3
{
public static partial class Vector3Ext
{
    public static UnityEngine.Vector3 Set(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] = value1;
        return target;
    }
    public static UnityEngine.Vector3 SetX(this UnityEngine.Vector3 target, float x) => Set(target, 0, x);
    public static UnityEngine.Vector3 SetY(this UnityEngine.Vector3 target, float y) => Set(target, 1, y);
    public static UnityEngine.Vector3 SetZ(this UnityEngine.Vector3 target, float z) => Set(target, 2, z);
    public static UnityEngine.Vector3 Set(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] = value1;
        target[axis2] = value2;
        return target;
    }
    public static UnityEngine.Vector3 SetXY(this UnityEngine.Vector3 target, float x, float y) => Set(target, 0, x, 1, y);
    public static UnityEngine.Vector3 SetXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Set(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 SetXZ(this UnityEngine.Vector3 target, float x, float z) => Set(target, 0, x, 2, z);
    public static UnityEngine.Vector3 SetXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Set(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 SetYZ(this UnityEngine.Vector3 target, float y, float z) => Set(target, 1, y, 2, z);
    public static UnityEngine.Vector3 SetYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Set(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Set(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] = value1;
        target[axis2] = value2;
        target[axis3] = value3;
        return target;
    }
    public static UnityEngine.Vector3 SetXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Set(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 SetXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Set(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Add(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] += value1;
        return target;
    }
    public static UnityEngine.Vector3 AddX(this UnityEngine.Vector3 target, float x) => Add(target, 0, x);
    public static UnityEngine.Vector3 AddY(this UnityEngine.Vector3 target, float y) => Add(target, 1, y);
    public static UnityEngine.Vector3 AddZ(this UnityEngine.Vector3 target, float z) => Add(target, 2, z);
    public static UnityEngine.Vector3 Add(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] += value1;
        target[axis2] += value2;
        return target;
    }
    public static UnityEngine.Vector3 AddXY(this UnityEngine.Vector3 target, float x, float y) => Add(target, 0, x, 1, y);
    public static UnityEngine.Vector3 AddXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Add(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 AddXZ(this UnityEngine.Vector3 target, float x, float z) => Add(target, 0, x, 2, z);
    public static UnityEngine.Vector3 AddXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Add(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 AddYZ(this UnityEngine.Vector3 target, float y, float z) => Add(target, 1, y, 2, z);
    public static UnityEngine.Vector3 AddYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Add(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Add(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] += value1;
        target[axis2] += value2;
        target[axis3] += value3;
        return target;
    }
    public static UnityEngine.Vector3 AddXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Add(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 AddXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Add(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Sub(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] -= value1;
        return target;
    }
    public static UnityEngine.Vector3 SubX(this UnityEngine.Vector3 target, float x) => Sub(target, 0, x);
    public static UnityEngine.Vector3 SubY(this UnityEngine.Vector3 target, float y) => Sub(target, 1, y);
    public static UnityEngine.Vector3 SubZ(this UnityEngine.Vector3 target, float z) => Sub(target, 2, z);
    public static UnityEngine.Vector3 Sub(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] -= value1;
        target[axis2] -= value2;
        return target;
    }
    public static UnityEngine.Vector3 SubXY(this UnityEngine.Vector3 target, float x, float y) => Sub(target, 0, x, 1, y);
    public static UnityEngine.Vector3 SubXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Sub(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 SubXZ(this UnityEngine.Vector3 target, float x, float z) => Sub(target, 0, x, 2, z);
    public static UnityEngine.Vector3 SubXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Sub(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 SubYZ(this UnityEngine.Vector3 target, float y, float z) => Sub(target, 1, y, 2, z);
    public static UnityEngine.Vector3 SubYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Sub(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Sub(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] -= value1;
        target[axis2] -= value2;
        target[axis3] -= value3;
        return target;
    }
    public static UnityEngine.Vector3 SubXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Sub(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 SubXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Sub(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Mul(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] *= value1;
        return target;
    }
    public static UnityEngine.Vector3 MulX(this UnityEngine.Vector3 target, float x) => Mul(target, 0, x);
    public static UnityEngine.Vector3 MulY(this UnityEngine.Vector3 target, float y) => Mul(target, 1, y);
    public static UnityEngine.Vector3 MulZ(this UnityEngine.Vector3 target, float z) => Mul(target, 2, z);
    public static UnityEngine.Vector3 Mul(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] *= value1;
        target[axis2] *= value2;
        return target;
    }
    public static UnityEngine.Vector3 MulXY(this UnityEngine.Vector3 target, float x, float y) => Mul(target, 0, x, 1, y);
    public static UnityEngine.Vector3 MulXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mul(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 MulXZ(this UnityEngine.Vector3 target, float x, float z) => Mul(target, 0, x, 2, z);
    public static UnityEngine.Vector3 MulXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mul(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 MulYZ(this UnityEngine.Vector3 target, float y, float z) => Mul(target, 1, y, 2, z);
    public static UnityEngine.Vector3 MulYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mul(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Mul(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] *= value1;
        target[axis2] *= value2;
        target[axis3] *= value3;
        return target;
    }
    public static UnityEngine.Vector3 MulXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Mul(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 MulXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Mul(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Div(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] /= value1;
        return target;
    }
    public static UnityEngine.Vector3 DivX(this UnityEngine.Vector3 target, float x) => Div(target, 0, x);
    public static UnityEngine.Vector3 DivY(this UnityEngine.Vector3 target, float y) => Div(target, 1, y);
    public static UnityEngine.Vector3 DivZ(this UnityEngine.Vector3 target, float z) => Div(target, 2, z);
    public static UnityEngine.Vector3 Div(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] /= value1;
        target[axis2] /= value2;
        return target;
    }
    public static UnityEngine.Vector3 DivXY(this UnityEngine.Vector3 target, float x, float y) => Div(target, 0, x, 1, y);
    public static UnityEngine.Vector3 DivXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Div(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 DivXZ(this UnityEngine.Vector3 target, float x, float z) => Div(target, 0, x, 2, z);
    public static UnityEngine.Vector3 DivXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Div(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 DivYZ(this UnityEngine.Vector3 target, float y, float z) => Div(target, 1, y, 2, z);
    public static UnityEngine.Vector3 DivYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Div(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Div(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] /= value1;
        target[axis2] /= value2;
        target[axis3] /= value3;
        return target;
    }
    public static UnityEngine.Vector3 DivXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Div(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 DivXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Div(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Mod(this UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] %= value1;
        return target;
    }
    public static UnityEngine.Vector3 ModX(this UnityEngine.Vector3 target, float x) => Mod(target, 0, x);
    public static UnityEngine.Vector3 ModY(this UnityEngine.Vector3 target, float y) => Mod(target, 1, y);
    public static UnityEngine.Vector3 ModZ(this UnityEngine.Vector3 target, float z) => Mod(target, 2, z);
    public static UnityEngine.Vector3 Mod(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] %= value1;
        target[axis2] %= value2;
        return target;
    }
    public static UnityEngine.Vector3 ModXY(this UnityEngine.Vector3 target, float x, float y) => Mod(target, 0, x, 1, y);
    public static UnityEngine.Vector3 ModXY(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mod(target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 ModXZ(this UnityEngine.Vector3 target, float x, float z) => Mod(target, 0, x, 2, z);
    public static UnityEngine.Vector3 ModXZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mod(target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 ModYZ(this UnityEngine.Vector3 target, float y, float z) => Mod(target, 1, y, 2, z);
    public static UnityEngine.Vector3 ModYZ(this UnityEngine.Vector3 target, UnityEngine.Vector2 value) => Mod(target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 Mod(this UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] %= value1;
        target[axis2] %= value2;
        target[axis3] %= value3;
        return target;
    }
    public static UnityEngine.Vector3 ModXYZ(this UnityEngine.Vector3 target, float x, float y, float z) => Mod(target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 ModXYZ(this UnityEngine.Vector3 target, UnityEngine.Vector3 value) => Mod(target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefSet(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] = value1;
        return target;
    }
    public static UnityEngine.Vector3 RefSetX(this ref UnityEngine.Vector3 target, float x) => RefSet(ref target, 0, x);
    public static UnityEngine.Vector3 RefSetY(this ref UnityEngine.Vector3 target, float y) => RefSet(ref target, 1, y);
    public static UnityEngine.Vector3 RefSetZ(this ref UnityEngine.Vector3 target, float z) => RefSet(ref target, 2, z);
    public static UnityEngine.Vector3 RefSet(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] = value1;
        target[axis2] = value2;
        return target;
    }
    public static UnityEngine.Vector3 RefSetXY(this ref UnityEngine.Vector3 target, float x, float y) => RefSet(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefSetXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSet(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefSetXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefSet(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefSetXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSet(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefSetYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefSet(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefSetYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSet(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefSet(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] = value1;
        target[axis2] = value2;
        target[axis3] = value3;
        return target;
    }
    public static UnityEngine.Vector3 RefSetXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefSet(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefSetXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefSet(ref target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefAdd(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] += value1;
        return target;
    }
    public static UnityEngine.Vector3 RefAddX(this ref UnityEngine.Vector3 target, float x) => RefAdd(ref target, 0, x);
    public static UnityEngine.Vector3 RefAddY(this ref UnityEngine.Vector3 target, float y) => RefAdd(ref target, 1, y);
    public static UnityEngine.Vector3 RefAddZ(this ref UnityEngine.Vector3 target, float z) => RefAdd(ref target, 2, z);
    public static UnityEngine.Vector3 RefAdd(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] += value1;
        target[axis2] += value2;
        return target;
    }
    public static UnityEngine.Vector3 RefAddXY(this ref UnityEngine.Vector3 target, float x, float y) => RefAdd(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefAddXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefAdd(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefAddXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefAdd(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefAddXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefAdd(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefAddYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefAdd(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefAddYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefAdd(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefAdd(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] += value1;
        target[axis2] += value2;
        target[axis3] += value3;
        return target;
    }
    public static UnityEngine.Vector3 RefAddXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefAdd(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefAddXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefAdd(ref target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefSub(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] -= value1;
        return target;
    }
    public static UnityEngine.Vector3 RefSubX(this ref UnityEngine.Vector3 target, float x) => RefSub(ref target, 0, x);
    public static UnityEngine.Vector3 RefSubY(this ref UnityEngine.Vector3 target, float y) => RefSub(ref target, 1, y);
    public static UnityEngine.Vector3 RefSubZ(this ref UnityEngine.Vector3 target, float z) => RefSub(ref target, 2, z);
    public static UnityEngine.Vector3 RefSub(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] -= value1;
        target[axis2] -= value2;
        return target;
    }
    public static UnityEngine.Vector3 RefSubXY(this ref UnityEngine.Vector3 target, float x, float y) => RefSub(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefSubXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSub(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefSubXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefSub(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefSubXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSub(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefSubYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefSub(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefSubYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefSub(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefSub(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] -= value1;
        target[axis2] -= value2;
        target[axis3] -= value3;
        return target;
    }
    public static UnityEngine.Vector3 RefSubXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefSub(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefSubXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefSub(ref target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefMul(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] *= value1;
        return target;
    }
    public static UnityEngine.Vector3 RefMulX(this ref UnityEngine.Vector3 target, float x) => RefMul(ref target, 0, x);
    public static UnityEngine.Vector3 RefMulY(this ref UnityEngine.Vector3 target, float y) => RefMul(ref target, 1, y);
    public static UnityEngine.Vector3 RefMulZ(this ref UnityEngine.Vector3 target, float z) => RefMul(ref target, 2, z);
    public static UnityEngine.Vector3 RefMul(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] *= value1;
        target[axis2] *= value2;
        return target;
    }
    public static UnityEngine.Vector3 RefMulXY(this ref UnityEngine.Vector3 target, float x, float y) => RefMul(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefMulXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMul(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefMulXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefMul(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefMulXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMul(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefMulYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefMul(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefMulYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMul(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefMul(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] *= value1;
        target[axis2] *= value2;
        target[axis3] *= value3;
        return target;
    }
    public static UnityEngine.Vector3 RefMulXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefMul(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefMulXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefMul(ref target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefDiv(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] /= value1;
        return target;
    }
    public static UnityEngine.Vector3 RefDivX(this ref UnityEngine.Vector3 target, float x) => RefDiv(ref target, 0, x);
    public static UnityEngine.Vector3 RefDivY(this ref UnityEngine.Vector3 target, float y) => RefDiv(ref target, 1, y);
    public static UnityEngine.Vector3 RefDivZ(this ref UnityEngine.Vector3 target, float z) => RefDiv(ref target, 2, z);
    public static UnityEngine.Vector3 RefDiv(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] /= value1;
        target[axis2] /= value2;
        return target;
    }
    public static UnityEngine.Vector3 RefDivXY(this ref UnityEngine.Vector3 target, float x, float y) => RefDiv(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefDivXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefDiv(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefDivXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefDiv(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefDivXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefDiv(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefDivYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefDiv(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefDivYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefDiv(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefDiv(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] /= value1;
        target[axis2] /= value2;
        target[axis3] /= value3;
        return target;
    }
    public static UnityEngine.Vector3 RefDivXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefDiv(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefDivXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefDiv(ref target, 0, value[0], 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefMod(this ref UnityEngine.Vector3 target, int axis1, float value1)
    {
        target[axis1] %= value1;
        return target;
    }
    public static UnityEngine.Vector3 RefModX(this ref UnityEngine.Vector3 target, float x) => RefMod(ref target, 0, x);
    public static UnityEngine.Vector3 RefModY(this ref UnityEngine.Vector3 target, float y) => RefMod(ref target, 1, y);
    public static UnityEngine.Vector3 RefModZ(this ref UnityEngine.Vector3 target, float z) => RefMod(ref target, 2, z);
    public static UnityEngine.Vector3 RefMod(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2)
    {
        target[axis1] %= value1;
        target[axis2] %= value2;
        return target;
    }
    public static UnityEngine.Vector3 RefModXY(this ref UnityEngine.Vector3 target, float x, float y) => RefMod(ref target, 0, x, 1, y);
    public static UnityEngine.Vector3 RefModXY(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMod(ref target, 0, value[0], 1, value[1]);
    public static UnityEngine.Vector3 RefModXZ(this ref UnityEngine.Vector3 target, float x, float z) => RefMod(ref target, 0, x, 2, z);
    public static UnityEngine.Vector3 RefModXZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMod(ref target, 0, value[0], 2, value[2]);
    public static UnityEngine.Vector3 RefModYZ(this ref UnityEngine.Vector3 target, float y, float z) => RefMod(ref target, 1, y, 2, z);
    public static UnityEngine.Vector3 RefModYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector2 value) => RefMod(ref target, 1, value[1], 2, value[2]);
    public static UnityEngine.Vector3 RefMod(this ref UnityEngine.Vector3 target, int axis1, float value1, int axis2, float value2, int axis3, float value3)
    {
        target[axis1] %= value1;
        target[axis2] %= value2;
        target[axis3] %= value3;
        return target;
    }
    public static UnityEngine.Vector3 RefModXYZ(this ref UnityEngine.Vector3 target, float x, float y, float z) => RefMod(ref target, 0, x, 1, y, 2, z);
    public static UnityEngine.Vector3 RefModXYZ(this ref UnityEngine.Vector3 target, UnityEngine.Vector3 value) => RefMod(ref target, 0, value[0], 1, value[1], 2, value[2]);
}
}
