// <auto-generated/>
// Generator: MathGetterGenerator (Level 3)
using UnityEngine;
namespace Showcase.Level3
{
public static partial class Vector3Ext
{
    public static UnityEngine.Vector2 Get(this UnityEngine.Vector3 target, int axis1, int axis2) => new(target[axis1], target[axis2]);
    public static UnityEngine.Vector2 GetXY(this UnityEngine.Vector3 target) => Get(target, 0, 1);
    public static UnityEngine.Vector2 GetXZ(this UnityEngine.Vector3 target) => Get(target, 0, 2);
    public static UnityEngine.Vector2 GetYZ(this UnityEngine.Vector3 target) => Get(target, 1, 2);
    public static UnityEngine.Vector2 GetXX(this UnityEngine.Vector3 target) => Get(target, 0, 0);
    public static UnityEngine.Vector2 GetYY(this UnityEngine.Vector3 target) => Get(target, 1, 1);
    public static UnityEngine.Vector2 GetZZ(this UnityEngine.Vector3 target) => Get(target, 2, 2);
    public static UnityEngine.Vector3 Get(this UnityEngine.Vector3 target, int axis1, int axis2, int axis3) => new(target[axis1], target[axis2], target[axis3]);
    public static UnityEngine.Vector3 GetXXX(this UnityEngine.Vector3 target) => Get(target, 0, 0, 0);
    public static UnityEngine.Vector3 GetYYY(this UnityEngine.Vector3 target) => Get(target, 1, 1, 1);
    public static UnityEngine.Vector3 GetZZZ(this UnityEngine.Vector3 target) => Get(target, 2, 2, 2);
}
}
