// <auto-generated/>
// Generator: AutoPropertyGenerator (Level 1)
namespace Showcase.Level1
{
    public partial class Level1Demo
    {
        public int Health
        {
            get => _health;
            set => _health = value;
        }

        public float MoveSpeed
        {
            get => _moveSpeed;
            set => _moveSpeed = value;
        }

        public string PlayerName
        {
            get => _playerName;
            set => _playerName = value;
        }

    }
}
