using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator.Infrastructure;

namespace Showcase.Generator.Level7;

/// <summary>
/// Level 7 — SchemaGenerator（第一阶段：提取 Attribute 信息生成描述文件）
///
/// 引入 API：
///   - MethodDeclarationSyntax     扫描方法级 Attribute（与之前扫描类/字段不同）
///
/// 生成内容：
///   [Event("player.died", typeof(PlayerData))] void OnPlayerDied(PlayerData data);
///     → 生成 ModuleMesh.Schema.g.cs（包含事件和工具的 Schema 注册表）
///
/// 关键教学：
///   - 方法级 Attribute 扫描：predicate 匹配 MethodDeclarationSyntax
///   - 两个 Generator 协作：分别注册，但共享信息（通过生成的描述类）
/// </summary>
[Generator]
public class SchemaGenerator : IIncrementalGenerator
{
    private const string EventAttributeFullName = "Showcase.Core.ModuleMesh.EventAttribute";
    private const string ToolAttributeFullName = "Showcase.Core.ModuleMesh.ToolAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.GenerateMode", out var mode);
                return GeneratorConfig.ParseMode(mode);
            }
        );

        // 关键点：predicate 现在匹配 MethodDeclarationSyntax（方法级 Attribute）
        var eventMethods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is MethodDeclarationSyntax m
                    && m.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetMethodInfo(ctx, EventAttributeFullName, "Event")
            )
            .Where(static t => t != null)
            .Select(static (t, _) => t!);

        var toolMethods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is MethodDeclarationSyntax m
                    && m.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetMethodInfo(ctx, ToolAttributeFullName, "Tool")
            )
            .Where(static t => t != null)
            .Select(static (t, _) => t!);

        // 聚合所有事件和工具方法后生成 Schema
        context.RegisterSourceOutput(
            eventMethods.Collect().Combine(toolMethods.Collect()).Combine(configProvider),
            static (ctx, t) => GenerateSchema(ctx, t.Left.Left, t.Left.Right, t.Right)
        );
    }

    private static MethodInfo? GetMethodInfo(
        GeneratorSyntaxContext context,
        string attributeFullName,
        string kind)
    {
        var method = (MethodDeclarationSyntax)context.Node;

        foreach (var attrList in method.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol attrSymbol)
                continue;

            if (attrSymbol.ContainingType.ToDisplayString() != attributeFullName)
                continue;

            // 读取 Attribute 的字符串参数
            var args = attr.ArgumentList?.Arguments;
            if (args == null || args.Value.Count < 2) continue;

            var name = args.Value[0].Expression is LiteralExpressionSyntax lit
                ? lit.Token.ValueText
                : args.Value[0].ToString().Trim('"');

            // typeof(X) 参数提取类型名
            var dataTypeName = args.Value[1].Expression is TypeOfExpressionSyntax typeOf
                ? typeOf.Type.ToString()
                : "object";

            // 获取方法所在类的全名
            var containingClass = method.Parent is TypeDeclarationSyntax parent
                ? context.SemanticModel.GetDeclaredSymbol(parent)?.ToDisplayString() ?? "Unknown"
                : "Unknown";

            return new MethodInfo(kind, name, dataTypeName,
                method.Identifier.Text, containingClass, method.SyntaxTree.FilePath);
        }

        return null;
    }

    private static void GenerateSchema(
        SourceProductionContext context,
        ImmutableArray<MethodInfo> events,
        ImmutableArray<MethodInfo> tools,
        GenerateMode mode)
    {
        if (events.IsEmpty && tools.IsEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generator: SchemaGenerator (Level 7 - Phase 1)");
        sb.AppendLine("// 此文件描述所有模块的事件和工具契约，供 ModuleCodeGenerator 读取");
        sb.AppendLine();
        sb.AppendLine("namespace Showcase.Generated.ModuleMesh");
        sb.AppendLine("{");

        // 生成事件 Schema 记录
        sb.AppendLine("    // ======= 事件契约 =======");
        foreach (var ev in events)
        {
            sb.AppendLine($"    // [Event] {ev.Name} on {ev.ContainingClass}.{ev.MethodName}");
            sb.AppendLine($"    // DataType: {ev.DataTypeName}");
        }
        sb.AppendLine();

        // 生成工具 Schema 记录
        sb.AppendLine("    // ======= 工具契约 =======");
        foreach (var tool in tools)
        {
            sb.AppendLine($"    // [Tool] {tool.Name} on {tool.ContainingClass}.{tool.MethodName}");
            sb.AppendLine($"    // DataType: {tool.DataTypeName}");
        }
        sb.AppendLine();

        // 生成 Schema 注册表
        sb.AppendLine("    /// <summary>所有模块事件和工具的编译期 Schema 注册表</summary>");
        sb.AppendLine("    public static class ModuleMeshSchema");
        sb.AppendLine("    {");

        sb.AppendLine("        public static readonly string[] EventNames = {");
        foreach (var ev in events)
            sb.AppendLine($"            \"{ev.Name}\",");
        sb.AppendLine("        };");
        sb.AppendLine();

        sb.AppendLine("        public static readonly string[] ToolNames = {");
        foreach (var tool in tools)
            sb.AppendLine($"            \"{tool.Name}\",");
        sb.AppendLine("        };");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        var source = sb.ToString();
        var fileName = "ModuleMesh.Schema.g.cs";

        // 从第一个事件或工具获取源文件路径
        var filePath = events.Length > 0 ? events[0].FilePath
            : tools.Length > 0 ? tools[0].FilePath
            : null;

        if (mode == GenerateMode.WriteFile && filePath != null)
        {
            FileWriter.WriteToPhysicalFile(context, filePath, fileName, source, "MESH");
        }
        else
        {
            context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private sealed class MethodInfo
    {
        public string Kind { get; }
        public string Name { get; }
        public string DataTypeName { get; }
        public string MethodName { get; }
        public string ContainingClass { get; }
        public string FilePath { get; }

        public MethodInfo(string kind, string name, string dataTypeName,
            string methodName, string containingClass, string filePath)
        {
            Kind = kind;
            Name = name;
            DataTypeName = dataTypeName;
            MethodName = methodName;
            ContainingClass = containingClass;
            FilePath = filePath;
        }
    }
}
